# Generated by Django 5.2.6 on 2025-09-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bonus_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
