# Generated by Django 5.2.6 on 2025-09-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_smscode_order_bonus_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smscode',
            name='code',
        ),
    ]
