# Generated by Django 5.2.6 on 2025-09-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_smscode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscode',
            name='code',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
