# Generated by Django 5.2.7 on 2025-10-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_remove_orderitem_dish_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='iiko_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_synced_with_iiko',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='iiko_organization_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
    ]
