# Generated by Django 5.2.7 on 2025-10-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_customer_iiko_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='iiko_organization_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_synced',
        ),
        migrations.AddField(
            model_name='order',
            name='order_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bonus_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
